sonar.projectName=strr
sonar.projectVersion=Autoscan

# Path to sources
#sonar.sources=strr-api/src/**/*
sonar.exclusions=strr-api/migrations/**/*,strr-api/devops/**/*,strr-api/tests/**/*,testing/**/*,queue_services/**/tests/**/*
#sonar.inclusions=

# Path to tests
#sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
# Sonar CPD exclusions only work at the file level for this shared database setup.
sonar.cpd.exclusions=strr-host-pm-web/tests/**, strr-host-pm-web/vitest.config.ts, strr-examiner-web/tests/**, jobs/auto-approval/src/auto_approval/config.py, jobs/batch-permit-validator/src/batch_permit_validator/config.py, jobs/noc_expiry/src/noc_expiry/config.py, jobs/provisional-approval/src/provisional_approval/config.py, jobs/registration_expiry/src/registration_expiry/config.py, jobs/renewal-reminders/src/renewal_reminders/config.py, jobs/strr-backfiller/src/backfiller/config.py
