version: '3.8'

services:
  webui:
    build:
      context: strr-web
      args:
        - DOT_ENV_FILE=.env.local
    ports:
      - "8000:80"
    env_file:
      - strr-web/.env.local
    networks:
      - web_tier
    depends_on:
          - api

  api:
    build:
      context: strr-api
    ports:
      - "8080:8080"
    env_file:
      - strr-api/.env.local
    networks:
      - web_tier
      - service_tier
    depends_on:
          - db

  db:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - service_tier

volumes:
  postgres-data:

networks:
  web_tier:
    name: web_tier
  service_tier:
    name: service_tier
