packages:
  - strr-examiner-web
  - strr-host-pm-web
  - strr-strata-web
  - strr-platform-web
  - strr-base-web
  - strr-web

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
