"""empty message

Revision ID: 758190173df9
Revises: 730a68e06df1
Create Date: 2024-10-10 05:39:01.095802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758190173df9'
down_revision = '730a68e06df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_brands_name'), ['name'], unique=False)

    op.create_table('platform_business_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_jurisdiction', sa.String(length=150), nullable=False),
    sa.Column('business_number', sa.String(length=150), nullable=True),
    sa.Column('cpbc_licence_number', sa.String(length=50), nullable=True),
    sa.Column('primary_non_compliance_notice_email', sa.String(length=100), nullable=False),
    sa.Column('secondary_non_compliance_notice_email', sa.String(length=100), nullable=True),
    sa.Column('primary_take_down_request_email', sa.String(length=100), nullable=False),
    sa.Column('secondary_take_down_request_email', sa.String(length=100), nullable=True),
    sa.Column('attorney_name', sa.String(length=150), nullable=True),
    sa.Column('listing_size', sa.Enum('GREATER_THAN_THOUSAND', 'LESS_THAN_THOUSAND', name='listingsize'), nullable=True),
    sa.Column('mailing_address_id', sa.Integer(), nullable=False),
    sa.Column('registered_office_attorney_mailing_address_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mailing_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['registered_office_attorney_mailing_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_registration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_representatives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_title', sa.String(), nullable=True))

    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_legal_name'), ['legal_name'], unique=False)
        batch_op.drop_constraint('platforms_registration_id_fkey', type_='foreignkey')
        batch_op.drop_column('registration_id')
        batch_op.drop_column('business_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_number', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('platforms_registration_id_fkey', 'registrations', ['registration_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_platforms_legal_name'))

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    op.drop_table('platform_representatives')
    op.drop_table('platform_registration')
    op.drop_table('platform_business_details')
    with op.batch_alter_table('platform_brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_brands_name'))

    op.drop_table('platform_brands')
    # ### end Alembic commands ###
