"""empty message

Revision ID: a3b1e7f5d0c9
Revises: 9c8f72d31a5e
Create Date: 2025-03-30 20:32:32.842000

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a3b1e7f5d0c9'
down_revision = '9c8f72d31a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        'idx_gin_application_json_path_ops',
        'application',
        ['application_json'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'application_json': 'jsonb_path_ops'}
    )
    op.create_index(
        'idx_gin_application_number_trgm',
        'application',
        ['application_number'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'application_number': 'gin_trgm_ops'}
    )
    op.create_index(
        'idx_gin_registration_number_trgm',
        'registrations',
        ['registration_number'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'registration_number': 'gin_trgm_ops'}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_gin_application_json_path_ops', table_name='application', postgresql_using='gin')
    op.drop_index('idx_gin_registration_number_trgm', table_name='registrations', postgresql_using='gin')
    op.drop_index('idx_gin_application_number_trgm', table_name='application', postgresql_using='gin')
    # ### end Alembic commands ###
