name: STRR APPLICATION AUTO APPROVAL JOB CI

on:
  pull_request:
    paths:
      - "jobs/auto-approval/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/auto-approval

jobs:
  strr-auto-approval-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "strr-auto-approval"
      working_directory: "./jobs/auto-approval"
      codecov_flag: "approvaljob"
