name: STRR EMAIL CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
      - release*
    paths:
      - "queue_services/strr-email/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - "dev"
          - "test"
          - "uat"
          - "sandbox"
          - "prod"
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  strr-email-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "strr-email"
      working_directory: "queue_services/strr-email"
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
