name: STRR APPLICATION AUTO APPROVAL JOB CD

on:
  push:
    branches:
      - main
    paths:
      - "jobs/auto-approval/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod

jobs:
  strr-application-auto-approval-job-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-job-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "strr-application-auto-approval-job"
      working_directory: "./jobs/auto-approval"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
