name: STRR PAY CI

on:
  pull_request:
    paths:
      - ".github/workflows/strr-pay-ci.yaml"
      - "shared/python/cloud-sql-connector/**"
      - "scripts/prepare-python-build-context.py"
      - ".github/workflows/strr-python-ci.yaml"
      - "queue_services/strr-pay/**"
      - "tests/python-test-utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/strr-pay

jobs:
  strr-pay-ci:
    uses: ./.github/workflows/strr-python-ci.yaml
    with:
      app_name: "strr-pay"
      working_directory: "./queue_services/strr-pay"
      codecov_flag: "strrpay"
      coverage_threshold: "80"
