name: STRR PLATFORM UI CD

on:
  push:
    branches:
      - main
    paths:
      - "strr-platform-web/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - prod

jobs:
  platform-ui-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "strr-platform-ui"
      working_directory: "./strr-platform-web"
      node_version: 20
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
