name: STRR STRATA UI CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
      - release*
    paths:
      - "strr-strata-web/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - "dev"
          - "test"
          - "sandbox"
          - "prod"
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  strata-ui-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "strr-strata-hotel-ui"
      working_directory: "./strr-strata-web"
      node_version: 20
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
