name: REGISTRATION EXPIRY JOB CI

on:
  pull_request:
    paths:
      - "jobs/registration_expiry/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/registration_expiry

jobs:
   registration-expiry-job-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: " registration-expiry-job-cd"
      working_directory: "./jobs/registration_expiry"
      codecov_flag: "regexpiryjob"
