name: STRR Examiner UI CI

on:
  pull_request:
    paths:
      - "strr-examiner-web/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./strr-examiner-web

jobs:
  examiner-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "strr-examiner-ui"
      working_directory: "./strr-examiner-web"
      codecov_flag: "strrexaminerui"
      node_version: 20
      pnpm_version: 10.0.0
