name: STRR Examiner UI CI
on:
  pull_request:
    paths:
      - "strr-examiner-web/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./strr-examiner-web

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          run_install: false

  examiner-ui-ci:
    needs: setup-env
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "strr-examiner-ui"
      working_directory: "./strr-examiner-web"
      codecov_flag: "strrexaminerui"
      node_version: 20
