name: STRR PAY CI

on:
  pull_request:
    paths:
      - "queue_services/strr-pay/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/strr-pay

jobs:
  strr-pay-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "strr-pay"
      working_directory: "./queue_services/strr-pay"
      codecov_flag: "strrpay"
