name: STRR INTERACTION UPDATES JOB CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
      - release*
    paths:
      - ".github/workflows/strr-interaction-updates-job-cd.yaml"
      - "shared/python/cloud-sql-connector/**"
      - "scripts/prepare-python-build-context.py"
      - "scripts/configure-iam-deployment.py"
      - ".github/workflows/strr-python-job-cd.yaml"
      - 'jobs/interactions-update/**'
  workflow_dispatch:
    inputs:
      target:
        description: 'Deploy To'
        required: true
        type: choice
        options:
          - 'dev'
          - 'test'
          - 'uat'
          - 'sandbox'
          - 'prod'
      redeploy:
        description: 'Redeploy Application'
        required: true
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  strr-interaction-updates-job-cd:
    uses: ./.github/workflows/strr-python-job-cd.yaml
    with:
      target: ${{ inputs.target }}
      app_name: 'strr-interactions-update'
      working_directory: './jobs/interactions-update'
      redeploy: ${{ inputs.redeploy }}
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
