name: BATCH PERMIT JOB CI

on:
  pull_request:
    paths:
      - ".github/workflows/strr-batch-validator-job-ci.yaml"
      - "shared/python/cloud-sql-connector/**"
      - "scripts/prepare-python-build-context.py"
      - ".github/workflows/strr-python-ci.yaml"
      - "jobs/batch-permit-validator/**"
      - "tests/python-test-utils/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/batch-permit-validator

jobs:
  batch-permit-job-ci:
    uses: ./.github/workflows/strr-python-ci.yaml
    with:
      app_name: "batch-permit-job"
      working_directory: "./jobs/batch-permit-validator"
      codecov_flag: "permitjob"
      coverage_threshold: "80"
