name: PROVISIONAL APPROVAL JOB CI

on:
  pull_request:
    paths:
      - ".github/workflows/strr-provisional-approval-job-ci.yaml"
      - "shared/python/cloud-sql-connector/**"
      - "scripts/prepare-python-build-context.py"
      - ".github/workflows/strr-python-ci.yaml"
      - "jobs/provisional-approval**"
      - "tests/python-test-utils/**"
      - "src/strr_api/models/**"
      - "src/strr_api/services/**"
      - "src/strr_api/enums/**"
      - "src/strr_api/exceptions/**"
      - "src/strr_api/utils/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./jobs/provisional-approval

jobs:
  provisional-approval-job-ci:
    uses: ./.github/workflows/strr-python-ci.yaml
    with:
      app_name: "provisional-approval-job"
      working_directory: "./jobs/provisional-approval"
      codecov_flag: "provisionalApprovaljob"
      coverage_threshold: "80"
